fixed sysupgrade (script always exits), updates setupos

diff --git a/infrastructure/bin/sysupgrade b/infrastructure/bin/sysupgrade
--- a/infrastructure/bin/sysupgrade
+++ b/infrastructure/bin/sysupgrade
@@ -438,7 +438,7 @@ unset showchanges
 # run
 case $1 in
     bootblocks)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         install_bootblocks
         ;;
     check)
@@ -446,7 +446,7 @@ case $1 in
         check_sum_all
         ;;
     update)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         sets_to_filenames
         run_hooks $HOOKS_PRE_DOWNLOAD
         download_files
@@ -460,7 +460,7 @@ case $1 in
 		fi
         ;;
     upgrade)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         sets_to_filenames
         if [ "$CHECKSUM_ON_UPGRADE" = "yes" ]; then
             check_sum_all || abort
@@ -474,7 +474,7 @@ case $1 in
         msg_final
         ;;
     post-reboot)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         sets_to_filenames
         run_hooks $HOOKS_POST_INSTALL
         check_reboot_backup
@@ -482,12 +482,12 @@ case $1 in
         msg_final
         ;;
     mergecfg)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         sets_to_filenames
         merge_etc
         ;;
     full)
-	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
+	[ `id -u` -ne 0 ] && echo "Root priveleges required." && exit 1
         sets_to_filenames
         run_hooks $HOOKS_PRE_DOWNLOAD
         download_files
