- set correct path to bsd.autotest.mk - add ${TEST} to all Makefiles - show name of package on installation - forbid sysupgrade run without root priveleges

diff --git a/infrastructure/bin/sysupgrade b/infrastructure/bin/sysupgrade
--- a/infrastructure/bin/sysupgrade
+++ b/infrastructure/bin/sysupgrade
@@ -3,6 +3,7 @@
 # Current version: 1.8 (2011-05-04)
 # https://github.com/jkossen/obu
 
+
 VERSION='54'
 NEW_BOOTBLOCKS="no"
 BOOTDISK='ad0'
@@ -179,9 +180,7 @@ download_files()
 
     cd "$DOWNLOADDIR" || fail
 
-    if [ ${MIRROR#file://} != $MIRROR ]; then
-        DFUN="download_file_file"
-    elif [ ${MIRROR#ftp://} != $MIRROR ]; then
+    if [ ${MIRROR#ftp://} != $MIRROR ]; then
         DFUN="download_file_ftp"
     elif [ ${MIRROR#http://} != $MIRROR ]; then
         DFUN="download_file_ftp"
@@ -439,6 +438,7 @@ unset showchanges
 # run
 case $1 in
     bootblocks)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         install_bootblocks
         ;;
     check)
@@ -446,6 +446,7 @@ case $1 in
         check_sum_all
         ;;
     update)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         sets_to_filenames
         run_hooks $HOOKS_PRE_DOWNLOAD
         download_files
@@ -459,6 +460,7 @@ case $1 in
 		fi
         ;;
     upgrade)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         sets_to_filenames
         if [ "$CHECKSUM_ON_UPGRADE" = "yes" ]; then
             check_sum_all || abort
@@ -472,6 +474,7 @@ case $1 in
         msg_final
         ;;
     post-reboot)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         sets_to_filenames
         run_hooks $HOOKS_POST_INSTALL
         check_reboot_backup
@@ -479,10 +482,12 @@ case $1 in
         msg_final
         ;;
     mergecfg)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         sets_to_filenames
         merge_etc
         ;;
     full)
+	[ `id -u` -ne 0 ] && echo "Root priveleges required."; exit 1
         sets_to_filenames
         run_hooks $HOOKS_PRE_DOWNLOAD
         download_files
